#cloud-config
write_files:
  - path: /etc/ops
    content: |
      AWS_REGION=<%= ENV['AWS_REGION'] %>
coreos:
  units:
  - name: web.service
    command: start
    content: |
      [Unit]
      Description=Dumpcomstock web page
      Requires=docker.service
      After=docker.service
      [Service]
      TimeoutStartSec=0
      Environment=AWS_REGION=<%= ENV['AWS_REGION'] %>
      Environment=REGISTRY=<%= parameters[:registry] %>
      ExecStartPre=/bin/bash -c 'eval $(docker run -e AWS_REGION rlister/ecr-login:latest)'
      ExecStartPre=-/usr/bin/docker rm %p
      ExecStartPre=/usr/bin/docker pull ${REGISTRY}/dumpcomstock:latest
      ExecStart=/usr/bin/docker run \
        --name %p \
        -p 80:80\
        ${REGISTRY}/dumpcomstock:latest
      ExecStop=/usr/bin/docker stop %p
      Restart=on-failure
      RestartSec=60